/**
 * Спецификация матрицы решений (FR-8, FR-5, FR-6, FR-7)
 * Единый источник данных для таблицы сравнения и карточного вида.
 */
const MATRIX_SPEC = {
  sections: [
    {
      id: "internal",
      label: "Внутренние решения (Inside POI)",
      fr: "FR-8.1.2, FR-8.1.3",
      rows: [
        {
          id: "poi_fluid",
          type: "poi_info",
          label: "Флюид",
          infoKey: "fluid",
          fr: "FR-4.2.10, FR-5.1.5",
        },
        {
          id: "poi_water_injection",
          type: "poi_info",
          label: "Объём закачки (вода)",
          infoKey: "water_injection",
          fr: "FR-4.2.11, FR-5.2.6",
        },
        {
          id: "autoroad",
          type: "subtype",
          label: "Автодорога",
          costType: "linear",
          variants: [
            { cost: 225, distance: 45, limit: 50, object: "Автодорога М-11", status: "within_limit" },
            { cost: 225, distance: 45, limit: 50, object: "Автодорога М-11", status: "within_limit" },
            { cost: 225, distance: 45, limit: 50, object: "Автодорога М-11", status: "within_limit" },
          ],
        },
        {
          id: "oil_pipeline",
          type: "subtype",
          label: "Нефтепровод",
          costType: "linear",
          variants: [
            { cost: 0, status: "not_required", object: "—" },
            { cost: 0, status: "not_required", object: "—" },
            { cost: 280, distance: 120, limit: 100, object: "НПЗ Север", status: "within_limit" },
          ],
        },
        {
          id: "water_pipeline",
          type: "subtype",
          label: "Водопровод",
          costType: "linear",
          variants: [
            { cost: 150, distance: 25, limit: 30, object: "Водовод-2", status: "within_limit" },
            { cost: 150, distance: 25, limit: 30, object: "Водовод-2", status: "within_limit" },
            { cost: 150, distance: 25, limit: 30, object: "Водовод-2", status: "within_limit" },
          ],
        },
        {
          id: "power_line",
          type: "subtype",
          label: "ЛЭП",
          costType: "linear",
          variants: [
            { cost: 84, distance: 28, limit: 30, object: "ЛЭП-35", status: "within_limit" },
            { cost: 84, distance: 28, limit: 30, object: "—", status: "construction_required" },
            { cost: 0, status: "not_required", object: "—" },
          ],
        },
        {
          id: "pads",
          type: "computed",
          label: "Кустовые площадки",
          costType: "pads",
          fr: "FR-5.3.2",
          variants: [
            { cost: 400, quantity: "2 шт. (5 скв.)", status: "within_limit" },
            { cost: 400, quantity: "2 шт.", status: "within_limit" },
            { cost: 400, quantity: "2 шт.", status: "within_limit" },
          ],
        },
        {
          id: "well_gathering",
          type: "engineering",
          label: "Сбор продукции скважин",
          engKey: "well_gathering",
          engClass: "gathering",
          fr: "FR-5.2.7",
          options: ["Однотрубная", "Двухтрубная", "Комбинированная"],
          activeIndex: [0, 0, 0],
        },
      ],
    },
    {
      id: "engineering",
      label: "Инженерные параметры",
      fr: "FR-8.1.3, FR-8.2.1–8.2.2",
      rows: [
        {
          id: "power",
          type: "engineering",
          label: "Электроснабжение",
          engKey: "power",
          engClass: "power",
          options: ["Внешнее", "Внутреннее"],
          activeIndex: [0, 0, 1],
          equipmentCost: [0, 0, 0],
        },
        {
          id: "injection",
          type: "engineering",
          label: "Закачка",
          engKey: "injection",
          engClass: "injection",
          options: ["Централизованная", "Локальная"],
          activeIndex: [0, 0, 1],
          equipmentCost: [0, 0, 150],
        },
        {
          id: "gas",
          type: "engineering",
          label: "Утилизация газа",
          engKey: "gas",
          engClass: "gas",
          options: ["В пласт", "Факел", "Электрогенерация"],
          activeIndex: [0, 0, 2],
          equipmentCost: [0, 0, 0],
        },
        {
          id: "oil_preparation",
          type: "engineering",
          label: "Подготовка нефти",
          engKey: "oil_preparation",
          engClass: "preparation",
          options: ["МКОС", "БМУПН", "ЦПС(УПН)", "УПСВ", "МФНС (без подготовки)"],
          activeIndex: [4, 4, 0],
          equipmentCost: [0, 0, 100],
        },
        {
          id: "transport",
          type: "engineering",
          label: "Транспортировка",
          engKey: "transport",
          engClass: "transport",
          options: ["Автовывоз", "Морской порт", "Магистральный трубопровод"],
          activeIndex: [0, 0, 2],
          equipmentCost: [0, 0, 0],
        },
      ],
    },
    {
      id: "external",
      label: "Внешние объекты (Outside POI)",
      fr: "FR-8.1.2, FR-8.1.4",
      rows: [
        {
          id: "gas_processing",
          type: "subtype",
          label: "ГКС",
          costType: "area",
          variants: [
            { cost: 500, distance: 92, limit: 80, object: "ГКС Восток", status: "exceeds_limit" },
            { cost: 500, distance: 92, limit: 80, object: "ГКС Восток", status: "exceeds_limit" },
            { cost: 500, distance: 92, limit: 80, object: "ГКС Восток", status: "exceeds_limit" },
          ],
        },
        {
          id: "gtes",
          type: "subtype",
          label: "ГТЭС / ГПЭС",
          costType: "area",
          variants: [
            { cost: 0, status: "not_required", object: "—" },
            { cost: 0, status: "not_required", object: "—" },
            { cost: 600, distance: 35, limit: 50, object: "ГТЭС-1", status: "within_limit" },
          ],
        },
        {
          id: "substation",
          type: "subtype",
          label: "ПС / ТП",
          costType: "area",
          variants: [
            { cost: 200, distance: 22, limit: 25, object: "ПС-110", status: "within_limit" },
            { cost: 200, distance: 22, limit: 25, object: "ПС-110", status: "within_limit" },
            { cost: 200, distance: 22, limit: 25, object: "ПС-110", status: "within_limit" },
          ],
        },
        {
          id: "refinery",
          type: "subtype",
          label: "НПЗ",
          costType: "area",
          variants: [
            { cost: 0, status: "not_required", object: "—" },
            { cost: 0, status: "not_required", object: "—" },
            { cost: 0, status: "not_required", object: "—", note: "в составе нефтепровода" },
          ],
        },
      ],
    },
    {
      id: "equipment",
      label: "Инженерное оборудование",
      fr: "FR-7.3.4",
      rows: [
        { id: "eq_power", type: "equipment", label: "Электроснабжение (внутр.)", variants: [{ cost: 0 }, { cost: 0 }, { cost: 450 }] },
        { id: "eq_injection", type: "equipment", label: "Локальная закачка", variants: [{ cost: 0 }, { cost: 0 }, { cost: 150, manual: true }] },
        { id: "eq_gas", type: "equipment", label: "Электрогенерация (газ)", variants: [{ cost: 0 }, { cost: 0 }, { cost: 0 }] },
        { id: "eq_oil_preparation", type: "equipment", label: "Подготовка нефти", variants: [{ cost: 0 }, { cost: 0 }, { cost: 100 }] },
        { id: "eq_transport", type: "equipment", label: "Транспортировка", variants: [{ cost: 0 }, { cost: 0 }, { cost: 0 }] },
      ],
    },
  ],
};

/** Карточки для шаблонного вида (выбранный / альтернативный) — по активному сценарию */
const MATRIX_CARD_MODULES = [
  { id: "oil_preparation", section: "engineering", title: "Подготовка нефти", engKey: "oil_preparation" },
  { id: "well_gathering", section: "internal", title: "Сбор скважин", engKey: "well_gathering" },
  { id: "power", section: "engineering", title: "Электроснабжение", engKey: "power" },
  { id: "injection", section: "engineering", title: "Система ППД", engKey: "injection" },
  { id: "gas_util", section: "engineering", title: "Утилизация газа", engKey: "gas", inGasBlock: true },
  { id: "gas_processing", section: "external", title: "ГКС", subtypeKey: "gas_processing", inGasBlock: true },
  { id: "transport", section: "engineering", title: "Транспортировка нефти", engKey: "transport" },
  { id: "autoroad", section: "internal", title: "Автодорога", subtypeKey: "autoroad" },
  { id: "oil_pipeline", section: "internal", title: "Нефтепровод", subtypeKey: "oil_pipeline" },
  { id: "water_pipeline", section: "internal", title: "Водопровод", subtypeKey: "water_pipeline" },
  { id: "power_line", section: "internal", title: "ЛЭП", subtypeKey: "power_line" },
  { id: "pads", section: "internal", title: "Кустовые площадки", subtypeKey: "pads" },
  { id: "gtes", section: "external", title: "ГТЭС / ГПЭС", subtypeKey: "gtes" },
  { id: "substation", section: "external", title: "ПС / ТП", subtypeKey: "substation" },
];
