import type { DrawMode, SelectMode } from '../../../components/MapView';
import type { POI } from '../../../lib/api';
import type { MapSearchHit } from '../../../lib/mapSearch';

export type MapPageToolbarProps = {
  map3dFeatureEnabled: boolean;
  mapDisplayMode: '2d' | '3d';
  onDisplayModeChange: (mode: '2d' | '3d') => void;
  mapLayersOpen: boolean;
  onToggleLayers: () => void;
  mapFullscreen: boolean;
  onToggleFullscreen: () => void;
  projectId: string | undefined;
  pois: POI[];
  selectedPoiId: string | null;
  onSelectedPoiIdChange: (id: string) => void;
  mapEditEnabled: boolean;
  onToggleMapEdit: () => void;
  canEditMap: boolean;
  mapIn3d: boolean;
  canUndo: boolean;
  onUndo: () => void;
  canCopy: boolean;
  onCopy: () => void;
  canPaste: boolean;
  onPaste: () => void;
  canCut: boolean;
  onCut: () => void;
  canDelete: boolean;
  selectedOnMapCount: number;
  deletePending: boolean;
  onDelete: () => void;
  drawMode: DrawMode;
  onDrawModeChange: (mode: DrawMode) => void;
  selectMode: SelectMode;
  onSelectModeChange: (mode: SelectMode) => void;
  onResetDrawingMenus: () => void;
  canWriteInfra: boolean;
  canWriteProject: boolean;
  projectJobBusy: boolean;
  infraFormSubtype: string;
  onInfraFormSubtypeChange: (subtype: string) => void;
  pointMenuOpen: boolean;
  onPointMenuOpenChange: (open: boolean) => void;
  lineMenuOpen: boolean;
  onLineMenuOpenChange: (open: boolean) => void;
  onClearLineDraft: () => void;
  onClearRuler: () => void;
  drawActionsVisible: boolean;
  drawStepBackDisabled: boolean;
  drawFinishDisabled: boolean;
  drawResetDisabled: boolean;
  onDrawStepBack: () => void;
  onDrawFinish: () => void;
  onDrawReset: () => void;
  searchQ: string;
  onSearchQChange: (q: string) => void;
  searchOpen: boolean;
  onSearchOpenChange: (open: boolean) => void;
  searchSuggestions: MapSearchHit[];
  onPickSearchResult: (hit: MapSearchHit) => void;
};
